services:
  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - web-network
  
  flask:
    container_name: flask
    build: ./flask
    depends_on:
      - mysql
    networks:
      - web-network
  
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - flask
    networks:
      - web-network

networks:
  web-network:

volumes:
  mysql-data:
